import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Import the generated API sidebar
const apiSidebar = require('./docs/api/sidebars.js');

const sidebars: SidebarsConfig = {
  // Tutorial sidebar - auto-generated from docs folder
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [{ type: 'autogenerated', dirName: 'tutorial-extras' }],
    },
  ],

  // API sidebar - imported from generated file
  apiSidebar: apiSidebar.apiSidebar,
};

export default sidebars;
