import { DocModel, Section, Subsection, Operation } from '../../transformer/types';

export interface SidebarItem {
  type: 'category' | 'doc' | 'link' | 'autogenerated';
  label?: string;
  id?: string; // For 'doc' type
  items?: SidebarItem[]; // For 'category' type
  link?: { type: 'generated-index' | 'doc'; id?: string }; // For category links
  collapsed?: boolean;
  collapsible?: boolean;
  className?: string;
  customProps?: Record<string, unknown>;
}

export type SidebarConfig = Record<string, SidebarItem[]>;

export class SidebarGenerator {
  generate(model: DocModel): SidebarItem[] {
    const sidebarItems: SidebarItem[] = [];

    for (const section of model.sections) {
      sidebarItems.push(this.generateSectionItem(section));
    }

    return sidebarItems;
  }

  private generateSectionItem(section: Section): SidebarItem {
    const sectionPath = this.slugify(section.name);
    const items: SidebarItem[] = [];

    for (const subsection of section.subsections) {
      if (subsection.name === '') {
        // Root subsection operations go directly into the section items
        for (const op of subsection.operations) {
          items.push(this.generateOperationItem(op, sectionPath));
        }
      } else {
        // Named subsections become nested categories
        items.push(this.generateSubsectionItem(subsection, sectionPath));
      }
    }

    return {
      type: 'category',
      label: section.name,
      link: {
        type: 'generated-index',
      },
      items: items,
      collapsible: true,
      collapsed: true,
    };
  }

  private generateSubsectionItem(subsection: Subsection, parentPath: string): SidebarItem {
    const subsectionSlug = this.slugify(subsection.name);
    const subsectionPath = `${parentPath}/${subsectionSlug}`;

    const items: SidebarItem[] = subsection.operations.map((op) =>
      this.generateOperationItem(op, subsectionPath)
    );

    return {
      type: 'category',
      label: subsection.name,
      link: {
        type: 'generated-index',
      },
      items: items,
      collapsible: true,
      collapsed: true,
    };
  }

  private generateOperationItem(operation: Operation, parentPath: string): SidebarItem {
    const opSlug = this.slugify(operation.name);
    return {
      type: 'doc',
      id: `${parentPath}/${opSlug}`,
      label: operation.name,
    };
  }

  private slugify(text: string): string {
    return text
      .replace(/([a-z])([A-Z])/g, '$1-$2') // Insert hyphen between camelCase
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)+/g, '');
  }
}
